apiVersion: apps/v1
kind: Deployment
metadata:
  name: wind-deployment
  labels:
    app: wind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wind
  template:
    metadata:
      labels:
        app: wind
    spec:
      containers:
        - name: wind-container
          image: wind:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wind
  labels:
    app: wind-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: wind
  sessionAffinity: None
